name: Secret scan (Gitleaks)

on:
  pull_request:
  push:
    branches: [ main, release/* ]
  schedule:
    - cron: "17 5 * * 1" # weekly Monday scan

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        uses: gitleaks/gitleaks-action@v1.6.0
        with:
          version: latest
          args: version

      - name: Run Gitleaks (fail on new secrets only)
        run: |
          gitleaks detect \
            --redact \
            --report-format sarif \
            --report-path gitleaks.sarif \
            --baseline-path .gitleaks.baseline.json || EXIT=$?
          # Exit with nonzero if new leaks were found
          if [ "${EXIT:-0}" != "0" ]; then exit $EXIT; fi

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

