name: Secret scan (Gitleaks)

on:
  pull_request:
  push:
    branches: [ main, release/* ]
  schedule:
    - cron: "17 5 * * 1" # weekly Monday scan

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and Execute Gitleaks
        uses: gitleaks/gitleaks-action@v1.6.0
        with:
          version: latest
          args: version
